version: 2
jobs:
  deploy:
    docker:
      - image: jumanjiman/aws:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run: echo "(」・ω・)」うー！"
      - run: aws s3 sync ./slide/outputs/ s3://yukpiz/ --exclude "*" --include "*.html"
      - run: aws s3 sync ./slide/reveal.js s3://yukpiz/
      - run: echo "(／・ω・)／にゃー！"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy