version: 2
jobs:
  build:
    docker:
      - image: jumanjiman/aws:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run echo "(」・ω・)」うー！"
      - run pwd
      - run type aws
      - run cat /etc/lsb-release
      - run echo "(／・ω・)／にゃー！"