version: 2
jobs:
  deploy:
    docker:
      - image: governmentpaas/awscli:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run: apk update
      - run: apk add git
      - run: git submodule update --init --recursive
      - run: echo "(」・ω・)」うー！"
      - run: aws s3 sync ./slide/outputs/ s3://yukpiz/ --exclude "*" --include "*.html"
      - run: aws s3 sync ./slide/reveal.js/css/ s3://yukpiz/reveal.js/css/
      - run: aws s3 sync ./slide/reveal.js/js/ s3://yukpiz/reveal.js/js/
      - run: aws s3 sync ./slide/reveal.js/lib/ s3://yukpiz/reveal.js/lib/
      - run: aws s3 sync ./slide/reveal.js/plugin/ s3://yukpiz/reveal.js/plugin/
      - run: echo "(／・ω・)／にゃー！"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy