version: 2
jobs:
  deploy:
    docker:
      - image: governmentpaas/awscli:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run: apk update
      - run: apk add git
      - run: git submodule update --init --recursive
      - run: echo "(」・ω・)」うー！"
      - run: aws s3 sync ./slide/outputs/ s3://yukpiz/ --exclude "*" --include "*.html"
      - run: aws s3 sync ./slide/reveal.js/ s3://yukpiz/reveal.js/
      - run: echo "(／・ω・)／にゃー！"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy