version: 2
jobs:
  deploy:
    docker:
      - image: jumanjiman/aws:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run: echo "(」・ω・)」うー！"
      - run: pwd
      - run: ls
      - run: echo "(／・ω・)／にゃー！"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy