version: 2
jobs:
  build:
    docker:
      - image: jumanjiman/aws:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run:
        name: test
        command: |
          echo "(」・ω・)」うー！"
          pwd
          type aws
          cat /etc/lsb-release
          echo "(／・ω・)／にゃー！"