version: 2
jobs:
  deploy:
    docker:
      - image: jumanjiman/aws:latest
    working_directory: ~/yukpiz
    steps:
      - checkout
      - run echo "(」・ω・)」うー！"
      - run pwd
      - run type aws
      - run cat /etc/lsb-release
      - run echo "(／・ω・)／にゃー！"

workflows:
  version: 2
  jobs:
    - deploy:
      filters:
        branches:
          only: master